version: 2
jobs:
      
 publish:
   docker:
     - image: circleci/openjdk:8u222-jdk-stretch
   steps:
     - checkout
     - setup_remote_docker:
          docker_layer_caching: true # - removed this feature from Free
     - run:
         name: Login to DockerHub
         command: docker login -u $DOCKER_USER -p $DOCKER_PASS
     - run: chmod +x gradlew && ./gradlew -Pprod bootJar jibDockerBuild
     - run: docker tag appname $DOCKER_USER/appname:$CIRCLE_BUILD_NUM
     - run: docker push $DOCKER_USER/appname:$CIRCLE_BUILD_NUM

workflows:
  version: 2
  Push_Image:
    jobs:
      - publish
